services:
  backend:
    container_name: backend
    build: ./creditos-api
    depends_on:
      - db
      - kafka
    ports:
      - "8080:8080"
    networks:
      - work
  db:
    image: postgres:16.2
    container_name: db
    environment:
      POSTGRES_DB: creditosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - volume-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - work
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - work
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - work
volumes:
  volume-postgres:

networks:
  work:
    driver: bridge
